################################################################################
# This file was auto-generated by generate_state_variable_form.py
################################################################################
import numpy as np


def calculate_eom(x, u, m_c, m_r, J_c, d, mu, g):
    [z, h, theta, zdot, hdot, thetadot] = x.flatten()  # ensure 1D
    [f_r, f_l] = u.flatten()  # ensure 1D
    eom = np.array([
        [zdot],
        [hdot],
        [thetadot],
        [-(f_l*np.sin(theta) + f_r*np.sin(theta) + mu*zdot)/(m_c + 2.0*m_r)],
        [(f_l*np.cos(theta) + f_r*np.cos(theta) - g*m_c - 2.0*g*m_r)/(m_c + 2.0*m_r)],
        [d*(-f_l + f_r)/(J_c + 2.0*d**2*m_r)]
    ])
    return eom.squeeze()
